### ISSUE TITLE
Method to stop listening to proximity events

### ISSUE THREAD

**Issue by abinmittu** [songyiYu/all_sensors#1]
Is there any way to unsubscribe or stop listening to proximity events when the view is disposed?

**Comment by songyiYu** [comment]
Thank you for your email. I've identified the issue. I'll be updating the
feature until late this week.

2019년 7월 10일 (수) 오후 1:19, Abin Baby <notifications@github.com>님이 작성:

**Comment by Pakuga** [comment]
Since [this example of @songyiYu ](https://github.com/songyiYu/all_sensors/blob/master/example/lib/main.dart )explains the way to stop listening to the stream, issue seems to be resolved.

Readme can be a little bit more explanatory and contain a link to the example  :)

Thanks for the efforts and quick fix!
